### ISSUE TITLE
Make use of library and tidy up fragmentation across repos

### ISSUE THREAD

**Issue by amateusz** [nothans/ESP8266#2]
So this caused me a lot of confusion and I'd rather save the others.
There is [this account](https://github.com/mathworks/thingspeak-arduino) which seems more like *your* official one.
It makes a fair use o your Thingspeak library from Arduino library repo.

The problem is, that right at the control panel of the service where is says:
> Examples
>* Arduino
>* Arduino MKR1000
>* ESP8266 
>* ...

:arrow_right: which links here.

Whereas this repo does some HTTP by hand, not making it clear how to add more `fields`, not mentioning that you can do GET request instead if you find whole POST troublesome. I tried to base my code on it and found non extensible.

**Comment by nothans** [comment]
Thanks for the comment. Would it help if I had an example that sends two Analog Input values to ThingSpeak? I intended not to use the library and demonstrate how to construct an HTTP request.
